using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using static Engine.GLFW;

namespace Engine
{
	public static class GL
	{
		static GL()
		{
			// Buffers
			glBindBuffer = GetDelegate<Delegates.glBindBuffer>();
			glBufferData = GetDelegate<Delegates.glBufferData>();
			glBufferSubData = GetDelegate<Delegates.glBufferSubData>();
			glDeleteBuffers = GetDelegate<Delegates.glDeleteBuffers>();
			glGenBuffers = GetDelegate<Delegates.glGenBuffers>();

			// Framebuffers
			glBindFramebuffer = GetDelegate<Delegates.glBindFramebuffer>();
			glBindRenderbuffer = GetDelegate<Delegates.glBindRenderbuffer>();
			glCheckFramebufferStatus = GetDelegate<Delegates.glCheckFramebufferStatus>();
			glDeleteFramebuffers = GetDelegate<Delegates.glDeleteFramebuffers>();
			glDeleteRenderbuffers = GetDelegate<Delegates.glDeleteRenderbuffers>();
			glDrawBuffer = GetDelegate<Delegates.glDrawBuffer>();
			glFramebufferRenderbuffer = GetDelegate<Delegates.glFramebufferRenderbuffer>();
			glFramebufferTexture2D = GetDelegate<Delegates.glFramebufferTexture2D>();
			glGenFramebuffers = GetDelegate<Delegates.glGenFramebuffers>();
			glGenRenderbuffers = GetDelegate<Delegates.glGenRenderbuffers>();
			glReadBuffer = GetDelegate<Delegates.glReadBuffer>();
			glRenderbufferStorage = GetDelegate<Delegates.glRenderbufferStorage>();

			// Other
			glCullFace = GetDelegate<Delegates.glCullFace>();
			glDisable = GetDelegate<Delegates.glDisable>();
			glEnable = GetDelegate<Delegates.glEnable>();

			// Rendering
			glBlendFunc = GetDelegate<Delegates.glBlendFunc>();
			glClear = GetDelegate<Delegates.glClear>();
			glClearColor = GetDelegate<Delegates.glClearColor>();
			glDepthFunc = GetDelegate<Delegates.glDepthFunc>();
			glDrawElements = GetDelegate<Delegates.glDrawElements>();
			glDrawElementsBaseVertex = GetDelegate<Delegates.glDrawElementsBaseVertex>();
			glPrimitiveRestartIndex = GetDelegate<Delegates.glPrimitiveRestartIndex>();
			glViewport = GetDelegate<Delegates.glViewport>();

			// Shaders
			glAttachShader = GetDelegate<Delegates.glAttachShader>();
			glBindVertexArray = GetDelegate<Delegates.glBindVertexArray>();
			glCompileShader = GetDelegate<Delegates.glCompileShader>();
			glCreateProgram = GetDelegate<Delegates.glCreateProgram>();
			glCreateShader = GetDelegate<Delegates.glCreateShader>();
			glDeleteProgram = GetDelegate<Delegates.glDeleteProgram>();
			glDeleteShader = GetDelegate<Delegates.glDeleteShader>();
			glDeleteVertexArrays = GetDelegate<Delegates.glDeleteVertexArrays>();
			glEnableVertexAttribArray = GetDelegate<Delegates.glEnableVertexAttribArray>();
			glGenVertexArrays = GetDelegate<Delegates.glGenVertexArrays>();
			glGetActiveUniform = GetDelegate<Delegates.glGetActiveUniform>();
			glGetProgramiv = GetDelegate<Delegates.glGetProgramiv>();
			glGetProgramInfoLog = GetDelegate<Delegates.glGetProgramInfoLog>();
			glGetShaderiv = GetDelegate<Delegates.glGetShaderiv>();
			glGetShaderInfoLog = GetDelegate<Delegates.glGetShaderInfoLog>();
			glGetUniformLocation = GetDelegate<Delegates.glGetUniformLocation>();
			glLinkProgram = GetDelegate<Delegates.glLinkProgram>();
			glShaderSource = GetDelegate<Delegates.glShaderSource>();
			glUniform1i= GetDelegate<Delegates.glUniform1i>();
			glUniform1f= GetDelegate<Delegates.glUniform1f>();
			glUniform3f= GetDelegate<Delegates.glUniform3f>();
			glUniform4f = GetDelegate<Delegates.glUniform4f>();
			glUniform4fv = GetDelegate<Delegates.glUniform4fv>();
			glUniformMatrix4fv = GetDelegate<Delegates.glUniformMatrix4fv>();
			glUseProgram = GetDelegate<Delegates.glUseProgram>();
			glVertexAttribIPointer = GetDelegate<Delegates.glVertexAttribIPointer>();
			glVertexAttribPointer = GetDelegate<Delegates.glVertexAttribPointer>();

			// Textures
			glActiveTexture = GetDelegate<Delegates.glActiveTexture>();
			glBindTexture = GetDelegate<Delegates.glBindTexture>();
			glDeleteTextures = GetDelegate<Delegates.glDeleteTextures>();
			glGenerateMipmap = GetDelegate<Delegates.glGenerateMipmap>();
			glGenTextures = GetDelegate<Delegates.glGenTextures>();
			glTexImage2D = GetDelegate<Delegates.glTexImage2D>();
			glTexParameteri = GetDelegate<Delegates.glTexParameteri>();
		}

		#region Constants

		public const int GL_DEPTH_BUFFER_BIT = 0x00000100;
		public const int GL_STENCIL_BUFFER_BIT = 0x0000040;
		public const int GL_COLOR_BUFFER_BIT = 0x00004000;
		public const int GL_FALSE = 0;
		public const int GL_TRUE = 1;
		public const int GL_POINTS = 0x0000;
		public const int GL_LINES = 0x0001;
		public const int GL_LINE_LOOP = 0x0002;
		public const int GL_LINE_STRIP = 0x0003;
		public const int GL_TRIANGLES = 0x0004;
		public const int GL_TRIANGLE_STRIP = 0x0005;
		public const int GL_TRIANGLE_FAN = 0x0006;
		public const int GL_NEVER = 0x0200;
		public const int GL_LESS = 0x0201;
		public const int GL_EQUAL = 0x0202;
		public const int GL_LEQUAL = 0x0203;
		public const int GL_GREATER = 0x0204;
		public const int GL_NOTEQUAL = 0x0205;
		public const int GL_GEQUAL = 0x0206;
		public const int GL_ALWAYS = 0x0207;
		public const int GL_BLEND_EQUATION_RGB = 0x8009;
		public const int GL_VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622;
		public const int GL_VERTEX_ATTRIB_ARRAY_SIZE = 0x8623;
		public const int GL_VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624;
		public const int GL_VERTEX_ATTRIB_ARRAY_TYPE = 0x8625;
		public const int GL_CURRENT_VERTEX_ATTRIB = 0x8626;
		public const int GL_VERTEX_PROGRAM_POINT_SIZE = 0x8642;
		public const int GL_VERTEX_ATTRIB_ARRAY_POINTER = 0x8645;
		public const int GL_STENCIL_BACK_FUNC = 0x8800;
		public const int GL_STENCIL_BACK_FAIL = 0x8801;
		public const int GL_STENCIL_BACK_PASS_DEPTH_FAIL = 0x8802;
		public const int GL_STENCIL_BACK_PASS_DEPTH_PASS = 0x8803;
		public const int GL_MAX_DRAW_BUFFERS = 0x8824;
		public const int GL_DRAW_BUFFER0 = 0x8825;
		public const int GL_DRAW_BUFFER1 = 0x8826;
		public const int GL_DRAW_BUFFER2 = 0x8827;
		public const int GL_DRAW_BUFFER3 = 0x8828;
		public const int GL_DRAW_BUFFER4 = 0x8829;
		public const int GL_DRAW_BUFFER5 = 0x882A;
		public const int GL_DRAW_BUFFER6 = 0x882B;
		public const int GL_DRAW_BUFFER7 = 0x882C;
		public const int GL_DRAW_BUFFER8 = 0x882D;
		public const int GL_DRAW_BUFFER9 = 0x882E;
		public const int GL_DRAW_BUFFER10 = 0x882F;
		public const int GL_DRAW_BUFFER11 = 0x8830;
		public const int GL_DRAW_BUFFER12 = 0x8831;
		public const int GL_DRAW_BUFFER13 = 0x8832;
		public const int GL_DRAW_BUFFER14 = 0x8833;
		public const int GL_DRAW_BUFFER15 = 0x8834;
		public const int GL_BLEND_EQUATION_ALPHA = 0x883D;
		public const int GL_MAX_VERTEX_ATTRIBS = 0x8869;
		public const int GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A;
		public const int GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872;
		public const int GL_FRAGMENT_SHADER = 0x8B30;
		public const int GL_GEOMETRY_SHADER = 0x8DD9;
		public const int GL_VERTEX_SHADER = 0x8B31;
		public const int GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49;
		public const int GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A;
		public const int GL_MAX_VARYING_FLOATS = 0x8B4B;
		public const int GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C;
		public const int GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D;
		public const int GL_SHADER_TYPE = 0x8B4F;
		public const int GL_FLOAT_VEC2 = 0x8B50;
		public const int GL_FLOAT_VEC3 = 0x8B51;
		public const int GL_FLOAT_VEC4 = 0x8B52;
		public const int GL_INT_VEC2 = 0x8B53;
		public const int GL_INT_VEC3 = 0x8B54;
		public const int GL_INT_VEC4 = 0x8B55;
		public const int GL_BOOL = 0x8B56;
		public const int GL_BOOL_VEC2 = 0x8B57;
		public const int GL_BOOL_VEC3 = 0x8B58;
		public const int GL_BOOL_VEC4 = 0x8B59;
		public const int GL_FLOAT_MAT2 = 0x8B5A;
		public const int GL_FLOAT_MAT3 = 0x8B5B;
		public const int GL_FLOAT_MAT4 = 0x8B5C;
		public const int GL_SAMPLER_1D = 0x8B5D;
		public const int GL_SAMPLER_2D = 0x8B5E;
		public const int GL_SAMPLER_3D = 0x8B5F;
		public const int GL_SAMPLER_CUBE = 0x8B60;
		public const int GL_SAMPLER_1D_SHADOW = 0x8B61;
		public const int GL_SAMPLER_2D_SHADOW = 0x8B62;
		public const int GL_DELETE_STATUS = 0x8B80;
		public const int GL_COMPILE_STATUS = 0x8B81;
		public const int GL_LINK_STATUS = 0x8B82;
		public const int GL_VALIDATE_STATUS = 0x8B83;
		public const int GL_INFO_LOG_LENGTH = 0x8B84;
		public const int GL_ATTACHED_SHADERS = 0x8B85;
		public const int GL_ACTIVE_UNIFORMS = 0x8B86;
		public const int GL_ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87;
		public const int GL_SHADER_SOURCE_LENGTH = 0x8B88;
		public const int GL_ACTIVE_ATTRIBUTES = 0x8B89;
		public const int GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A;
		public const int GL_FRAGMENT_SHADER_DERIVATIVE_HINT = 0x8B8B;
		public const int GL_SHADING_LANGUAGE_VERSION = 0x8B8C;
		public const int GL_CURRENT_PROGRAM = 0x8B8D;
		public const int GL_POINT_SPRITE_COORD_ORIGIN = 0x8CA0;
		public const int GL_LOWER_LEFT = 0x8CA1;
		public const int GL_UPPER_LEFT = 0x8CA2;
		public const int GL_STENCIL_BACK_REF = 0x8CA3;
		public const int GL_STENCIL_BACK_VALUE_MASK = 0x8CA4;
		public const int GL_STENCIL_BACK_WRITEMASK = 0x8CA5;
		public const int GL_VERTEX_PROGRAM_TWO_SIDE = 0x8643;
		public const int GL_POINT_SPRITE = 0x8861;
		public const int GL_COORD_REPLACE = 0x8862;
		public const int GL_MAX_TEXTURE_COORDS = 0x8871;
		public const int GL_ZERO = 0;
		public const int GL_ONE = 1;
		public const int GL_SRC_COLOR = 0x0300;
		public const int GL_ONE_MINUS_SRC_COLOR = 0x0301;
		public const int GL_SRC_ALPHA = 0x0302;
		public const int GL_ONE_MINUS_SRC_ALPHA = 0x0303;
		public const int GL_DST_ALPHA = 0x0304;
		public const int GL_ONE_MINUS_DST_ALPHA = 0x0305;
		public const int GL_DST_COLOR = 0x0306;
		public const int GL_ONE_MINUS_DST_COLOR = 0x0307;
		public const int GL_SRC_ALPHA_SATURATE = 0x0308;
		public const int GL_FRONT = 0x0404;
		public const int GL_BACK = 0x0405;
		public const int GL_FRONT_AND_BACK = 0x0408;
		public const int GL_FOG = 0x0B60;
		public const int GL_LIGHTING = 0x0B50;
		public const int GL_TEXTURE_2D = 0x0DE1;
		public const int GL_CULL_FACE = 0x0B44;
		public const int GL_ALPHA_TEST = 0x0BC0;
		public const int GL_BLEND = 0x0BE2;
		public const int GL_COLOR_LOGIC_OP = 0x0BF2;
		public const int GL_DITHER = 0x0BD0;
		public const int GL_STENCIL_TEST = 0x0B90;
		public const int GL_DEPTH_TEST = 0x0B71;
		public const int GL_POINT_SMOOTH = 0x0B10;
		public const int GL_LINE_SMOOTH = 0x0B20;
		public const int GL_SCISSOR_TEST = 0x0C11;
		public const int GL_COLOR_MATERIAL = 0x0B57;
		public const int GL_NORMALIZE = 0x0BA1;
		public const int GL_RESCALE_NORMAL = 0x803A;
		public const int GL_POLYGON_OFFSET_FILL = 0x8037;
		public const int GL_VERTEX_ARRAY = 0x8074;
		public const int GL_NORMAL_ARRAY = 0x8075;
		public const int GL_COLOR_ARRAY = 0x8076;
		public const int GL_TEXTURE_COORD_ARRAY = 0x8078;
		public const int GL_MULTISAMPLE = 0x809D;
		public const int GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E;
		public const int GL_SAMPLE_ALPHA_TO_ONE = 0x809F;
		public const int GL_SAMPLE_COVERAGE = 0x80A0;
		public const int GL_NO_ERROR = 0;
		public const int GL_INVALID_ENUM = 0x0500;
		public const int GL_INVALID_VALUE = 0x0501;
		public const int GL_INVALID_OPERATION = 0x0502;
		public const int GL_STACK_OVERFLOW = 0x0503;
		public const int GL_STACK_UNDERFLOW = 0x0504;
		public const int GL_OUT_OF_MEMORY = 0x0505;
		public const int GL_EXP = 0x0800;
		public const int GL_EXP2 = 0x0801;
		public const int GL_FOG_DENSITY = 0x0B62;
		public const int GL_FOG_START = 0x0B63;
		public const int GL_FOG_END = 0x0B64;
		public const int GL_FOG_MODE = 0x0B65;
		public const int GL_FOG_COLOR = 0x0B66;
		public const int GL_CW = 0x0900;
		public const int GL_CCW = 0x0901;
		public const int GL_SMOOTH_POINT_SIZE_RANGE = 0x0B12;
		public const int GL_SMOOTH_LINE_WIDTH_RANGE = 0x0B22;
		public const int GL_ALIASED_POINT_SIZE_RANGE = 0x846D;
		public const int GL_ALIASED_LINE_WIDTH_RANGE = 0x846E;
		public const int GL_IMPLEMENTATION_COLOR_READ_TYPE_OES = 0x8B9A;
		public const int GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES = 0x8B9B;
		public const int GL_MAX_LIGHTS = 0x0D31;
		public const int GL_MAX_TEXTURE_SIZE = 0x0D33;
		public const int GL_MAX_MODELVIEW_STACK_DEPTH = 0x0D36;
		public const int GL_MAX_PROJECTION_STACK_DEPTH = 0x0D38;
		public const int GL_MAX_TEXTURE_STACK_DEPTH = 0x0D39;
		public const int GL_MAX_VIEWPORT_DIMS = 0x0D3A;
		public const int GL_MAX_ELEMENTS_VERTICES = 0x80E8;
		public const int GL_MAX_ELEMENTS_INDICES = 0x80E9;
		public const int GL_MAX_TEXTURE_UNITS = 0x84E2;
		public const int GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2;
		public const int GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3;
		public const int GL_SUBPIXEL_BITS = 0x0D50;
		public const int GL_RED_BITS = 0x0D52;
		public const int GL_GREEN_BITS = 0x0D53;
		public const int GL_BLUE_BITS = 0x0D54;
		public const int GL_ALPHA_BITS = 0x0D55;
		public const int GL_DEPTH_BITS = 0x0D56;
		public const int GL_STENCIL_BITS = 0x0D57;
		public const int GL_DONT_CARE = 0x1100;
		public const int GL_FASTEST = 0x1101;
		public const int GL_NICEST = 0x1102;
		public const int GL_PERSPECTIVE_CORRECTION_HINT = 0x0C50;
		public const int GL_POINT_SMOOTH_HINT = 0x0C51;
		public const int GL_LINE_SMOOTH_HINT = 0x0C52;
		public const int GL_POLYGON_SMOOTH_HINT = 0x0C53;
		public const int GL_FOG_HINT = 0x0C54;
		public const int GL_LIGHT_MODEL_AMBIENT = 0x0B53;
		public const int GL_LIGHT_MODEL_TWO_SIDE = 0x0B52;
		public const int GL_AMBIENT = 0x1200;
		public const int GL_DIFFUSE = 0x1201;
		public const int GL_SPECULAR = 0x1202;
		public const int GL_POSITION = 0x1203;
		public const int GL_SPOT_DIRECTION = 0x1204;
		public const int GL_SPOT_EXPONENT = 0x1205;
		public const int GL_SPOT_CUTOFF = 0x1206;
		public const int GL_CONSTANT_ATTENUATION = 0x1207;
		public const int GL_LINEAR_ATTENUATION = 0x1208;
		public const int GL_QUADRATIC_ATTENUATION = 0x1209;
		public const int GL_BYTE = 0x1400;
		public const int GL_UNSIGNED_BYTE = 0x1401;
		public const int GL_SHORT = 0x1402;
		public const int GL_UNSIGNED_SHORT = 0x1403;
		public const int GL_FLOAT = 0x1406;
		public const int GL_FIXED = 0x140C;
		public const int GL_CLEAR = 0x1500;
		public const int GL_AND = 0x1501;
		public const int GL_AND_REVERSE = 0x1502;
		public const int GL_COPY = 0x1503;
		public const int GL_AND_INVERTED = 0x1504;
		public const int GL_NOOP = 0x1505;
		public const int GL_XOR = 0x1506;
		public const int GL_OR = 0x1507;
		public const int GL_NOR = 0x1508;
		public const int GL_EQUIV = 0x1509;
		public const int GL_INVERT = 0x150A;
		public const int GL_OR_REVERSE = 0x150B;
		public const int GL_COPY_INVERTED = 0x150C;
		public const int GL_OR_INVERTED = 0x150D;
		public const int GL_NAND = 0x150E;
		public const int GL_SET = 0x150F;
		public const int GL_EMISSION = 0x1600;
		public const int GL_SHININESS = 0x1601;
		public const int GL_AMBIENT_AND_DIFFUSE = 0x1602;
		public const int GL_MODELVIEW = 0x1700;
		public const int GL_PROJECTION = 0x1701;
		public const int GL_TEXTURE = 0x1702;
		public const int GL_ALPHA = 0x1906;
		public const int GL_RGB = 0x1907;
		public const int GL_RGBA = 0x1908;
		public const int GL_LUMINANCE = 0x1909;
		public const int GL_LUMINANCE_ALPHA = 0x190A;
		public const int GL_UNPACK_ALIGNMENT = 0x0CF5;
		public const int GL_PACK_ALIGNMENT = 0x0D05;
		public const int GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033;
		public const int GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034;
		public const int GL_UNSIGNED_SHORT_5_6_5 = 0x8363;
		public const int GL_FLAT = 0x1D00;
		public const int GL_SMOOTH = 0x1D01;
		public const int GL_KEEP = 0x1E00;
		public const int GL_REPLACE = 0x1E01;
		public const int GL_INCR = 0x1E02;
		public const int GL_DECR = 0x1E03;
		public const int GL_VENDOR = 0x1F00;
		public const int GL_RENDERER = 0x1F01;
		public const int GL_VERSION = 0x1F02;
		public const int GL_EXTENSIONS = 0x1F03;
		public const int GL_MODULATE = 0x2100;
		public const int GL_DECAL = 0x2101;
		public const int GL_ADD = 0x0104;
		public const int GL_TEXTURE_ENV_MODE = 0x2200;
		public const int GL_TEXTURE_ENV_COLOR = 0x2201;
		public const int GL_TEXTURE_ENV = 0x2300;
		public const int GL_NEAREST = 0x2600;
		public const int GL_LINEAR = 0x2601;
		public const int GL_NEAREST_MIPMAP_NEAREST = 0x2700;
		public const int GL_LINEAR_MIPMAP_NEAREST = 0x2701;
		public const int GL_NEAREST_MIPMAP_LINEAR = 0x2702;
		public const int GL_LINEAR_MIPMAP_LINEAR = 0x2703;
		public const int GL_TEXTURE_MAG_FILTER = 0x2800;
		public const int GL_TEXTURE_MIN_FILTER = 0x2801;
		public const int GL_TEXTURE_WRAP_S = 0x2802;
		public const int GL_TEXTURE_WRAP_T = 0x2803;
		public const int GL_TEXTURE0 = 0x84C0;
		public const int GL_TEXTURE1 = 0x84C1;
		public const int GL_TEXTURE2 = 0x84C2;
		public const int GL_TEXTURE3 = 0x84C3;
		public const int GL_TEXTURE4 = 0x84C4;
		public const int GL_TEXTURE5 = 0x84C5;
		public const int GL_TEXTURE6 = 0x84C6;
		public const int GL_TEXTURE7 = 0x84C7;
		public const int GL_TEXTURE8 = 0x84C8;
		public const int GL_TEXTURE9 = 0x84C9;
		public const int GL_TEXTURE10 = 0x84CA;
		public const int GL_TEXTURE11 = 0x84CB;
		public const int GL_TEXTURE12 = 0x84CC;
		public const int GL_TEXTURE13 = 0x84CD;
		public const int GL_TEXTURE14 = 0x84CE;
		public const int GL_TEXTURE15 = 0x84CF;
		public const int GL_TEXTURE16 = 0x84D0;
		public const int GL_TEXTURE17 = 0x84D1;
		public const int GL_TEXTURE18 = 0x84D2;
		public const int GL_TEXTURE19 = 0x84D3;
		public const int GL_TEXTURE20 = 0x84D4;
		public const int GL_TEXTURE21 = 0x84D5;
		public const int GL_TEXTURE22 = 0x84D6;
		public const int GL_TEXTURE23 = 0x84D7;
		public const int GL_TEXTURE24 = 0x84D8;
		public const int GL_TEXTURE25 = 0x84D9;
		public const int GL_TEXTURE26 = 0x84DA;
		public const int GL_TEXTURE27 = 0x84DB;
		public const int GL_TEXTURE28 = 0x84DC;
		public const int GL_TEXTURE29 = 0x84DD;
		public const int GL_TEXTURE30 = 0x84DE;
		public const int GL_TEXTURE31 = 0x84DF;
		public const int GL_REPEAT = 0x2901;
		public const int GL_CLAMP_TO_EDGE = 0x812F;
		public const int GL_PALETTE4_RGB8_OES = 0x8B90;
		public const int GL_PALETTE4_RGBA8_OES = 0x8B91;
		public const int GL_PALETTE4_R5_G6_B5_OES = 0x8B92;
		public const int GL_PALETTE4_RGBA4_OES = 0x8B93;
		public const int GL_PALETTE4_RGB5_A1_OES = 0x8B94;
		public const int GL_PALETTE8_RGB8_OES = 0x8B95;
		public const int GL_PALETTE8_RGBA8_OES = 0x8B96;
		public const int GL_PALETTE8_R5_G6_B5_OES = 0x8B97;
		public const int GL_PALETTE8_RGBA4_OES = 0x8B98;
		public const int GL_PALETTE8_RGB5_A1_OES = 0x8B99;
		public const int GL_LIGHT0 = 0x4000;
		public const int GL_LIGHT1 = 0x4001;
		public const int GL_LIGHT2 = 0x4002;
		public const int GL_LIGHT3 = 0x4003;
		public const int GL_LIGHT4 = 0x4004;
		public const int GL_LIGHT5 = 0x4005;
		public const int GL_LIGHT6 = 0x4006;
		public const int GL_LIGHT7 = 0x4007;
		public const int GL_BUFFER_SIZE = 0x8764;
		public const int GL_BUFFER_USAGE = 0x8765;
		public const int GL_QUERY_COUNTER_BITS = 0x8864;
		public const int GL_CURRENT_QUERY = 0x8865;
		public const int GL_QUERY_RESULT = 0x8866;
		public const int GL_QUERY_RESULT_AVAILABLE = 0x8867;
		public const int GL_ARRAY_BUFFER = 0x8892;
		public const int GL_ELEMENT_ARRAY_BUFFER = 0x8893;
		public const int GL_ARRAY_BUFFER_BINDING = 0x8894;
		public const int GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895;
		public const int GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0x889F;
		public const int GL_READ_ONLY = 0x88B8;
		public const int GL_WRITE_ONLY = 0x88B9;
		public const int GL_READ_WRITE = 0x88BA;
		public const int GL_BUFFER_ACCESS = 0x88BB;
		public const int GL_BUFFER_MAPPED = 0x88BC;
		public const int GL_BUFFER_MAP_POINTER = 0x88BD;
		public const int GL_STREAM_DRAW = 0x88E0;
		public const int GL_STREAM_READ = 0x88E1;
		public const int GL_STREAM_COPY = 0x88E2;
		public const int GL_STATIC_DRAW = 0x88E4;
		public const int GL_STATIC_READ = 0x88E5;
		public const int GL_STATIC_COPY = 0x88E6;
		public const int GL_DYNAMIC_DRAW = 0x88E8;
		public const int GL_DYNAMIC_READ = 0x88E9;
		public const int GL_DYNAMIC_COPY = 0x88EA;
		public const int GL_SAMPLES_PASSED = 0x8914;
		public const int GL_SRC1_ALPHA = 0x8589;
		public const int GL_VERTEX_ARRAY_BUFFER_BINDING = 0x8896;
		public const int GL_NORMAL_ARRAY_BUFFER_BINDING = 0x8897;
		public const int GL_COLOR_ARRAY_BUFFER_BINDING = 0x8898;
		public const int GL_INDEX_ARRAY_BUFFER_BINDING = 0x8899;
		public const int GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = 0x889A;
		public const int GL_EDGE_FLAG_ARRAY_BUFFER_BINDING = 0x889B;
		public const int GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING = 0x889C;
		public const int GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING = 0x889D;
		public const int GL_WEIGHT_ARRAY_BUFFER_BINDING = 0x889E;
		public const int GL_FOG_COORD_SRC = 0x8450;
		public const int GL_FOG_COORD = 0x8451;
		public const int GL_CURRENT_FOG_COORD = 0x8453;
		public const int GL_FOG_COORD_ARRAY_TYPE = 0x8454;
		public const int GL_FOG_COORD_ARRAY_STRIDE = 0x8455;
		public const int GL_FOG_COORD_ARRAY_POINTER = 0x8456;
		public const int GL_FOG_COORD_ARRAY = 0x8457;
		public const int GL_FOG_COORD_ARRAY_BUFFER_BINDING = 0x889D;
		public const int GL_SRC0_RGB = 0x8580;
		public const int GL_SRC1_RGB = 0x8581;
		public const int GL_SRC2_RGB = 0x8582;
		public const int GL_SRC0_ALPHA = 0x8588;
		public const int GL_SRC2_ALPHA = 0x858A;
		public const int GL_SAMPLER_2D_RECT = 0x8B63;
		public const int GL_SAMPLER_2D_RECT_SHADOW = 0x8B64;
		public const int GL_SAMPLER_BUFFER = 0x8DC2;
		public const int GL_INT_SAMPLER_2D_RECT = 0x8DCD;
		public const int GL_INT_SAMPLER_BUFFER = 0x8DD0;
		public const int GL_UNSIGNED_INT_SAMPLER_2D_RECT = 0x8DD5;
		public const int GL_UNSIGNED_INT_SAMPLER_BUFFER = 0x8DD8;
		public const int GL_TEXTURE_BUFFER = 0x8C2A;
		public const int GL_MAX_TEXTURE_BUFFER_SIZE = 0x8C2B;
		public const int GL_TEXTURE_BINDING_BUFFER = 0x8C2C;
		public const int GL_TEXTURE_BUFFER_DATA_STORE_BINDING = 0x8C2D;
		public const int GL_TEXTURE_RECTANGLE = 0x84F5;
		public const int GL_TEXTURE_BINDING_RECTANGLE = 0x84F6;
		public const int GL_PROXY_TEXTURE_RECTANGLE = 0x84F7;
		public const int GL_MAX_RECTANGLE_TEXTURE_SIZE = 0x84F8;
		public const int GL_R8_SNORM = 0x8F94;
		public const int GL_RG8_SNORM = 0x8F95;
		public const int GL_RGB8_SNORM = 0x8F96;
		public const int GL_RGBA8_SNORM = 0x8F97;
		public const int GL_R16_SNORM = 0x8F98;
		public const int GL_RG16_SNORM = 0x8F99;
		public const int GL_RGB16_SNORM = 0x8F9A;
		public const int GL_RGBA16_SNORM = 0x8F9B;
		public const int GL_SIGNED_NORMALIZED = 0x8F9C;
		public const int GL_PRIMITIVE_RESTART = 0x8F9D;
		public const int GL_PRIMITIVE_RESTART_INDEX = 0x8F9E;
		public const int GL_COPY_READ_BUFFER = 0x8F36;
		public const int GL_COPY_WRITE_BUFFER = 0x8F37;
		public const int GL_UNIFORM_BUFFER = 0x8A11;
		public const int GL_UNIFORM_BUFFER_BINDING = 0x8A28;
		public const int GL_UNIFORM_BUFFER_START = 0x8A29;
		public const int GL_UNIFORM_BUFFER_SIZE = 0x8A2A;
		public const int GL_MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2B;
		public const int GL_MAX_GEOMETRY_UNIFORM_BLOCKS = 0x8A2C;
		public const int GL_MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2D;
		public const int GL_MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2E;
		public const int GL_MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2F;
		public const int GL_MAX_UNIFORM_BLOCK_SIZE = 0x8A30;
		public const int GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = 0x8A31;
		public const int GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS = 0x8A32;
		public const int GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = 0x8A33;
		public const int GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 0x8A34;
		public const int GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = 0x8A35;
		public const int GL_ACTIVE_UNIFORM_BLOCKS = 0x8A36;
		public const int GL_UNIFORM_TYPE = 0x8A37;
		public const int GL_UNIFORM_SIZE = 0x8A38;
		public const int GL_UNIFORM_NAME_LENGTH = 0x8A39;
		public const int GL_UNIFORM_BLOCK_INDEX = 0x8A3A;
		public const int GL_UNIFORM_OFFSET = 0x8A3B;
		public const int GL_UNIFORM_ARRAY_STRIDE = 0x8A3C;
		public const int GL_UNIFORM_MATRIX_STRIDE = 0x8A3D;
		public const int GL_UNIFORM_IS_ROW_MAJOR = 0x8A3E;
		public const int GL_UNIFORM_BLOCK_BINDING = 0x8A3F;
		public const int GL_UNIFORM_BLOCK_DATA_SIZE = 0x8A40;
		public const int GL_UNIFORM_BLOCK_NAME_LENGTH = 0x8A41;
		public const int GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = 0x8A42;
		public const int GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = 0x8A43;
		public const int GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = 0x8A44;
		public const int GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER = 0x8A45;
		public const int GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = 0x8A46;
		public const int GL_COMPARE_REF_TO_TEXTURE = 0x884E;
		public const int GL_CLIP_DISTANCE0 = 0x3000;
		public const int GL_CLIP_DISTANCE1 = 0x3001;
		public const int GL_CLIP_DISTANCE2 = 0x3002;
		public const int GL_CLIP_DISTANCE3 = 0x3003;
		public const int GL_CLIP_DISTANCE4 = 0x3004;
		public const int GL_CLIP_DISTANCE5 = 0x3005;
		public const int GL_CLIP_DISTANCE6 = 0x3006;
		public const int GL_CLIP_DISTANCE7 = 0x3007;
		public const int GL_MAX_CLIP_DISTANCES = 0x0D32;
		public const int GL_MAJOR_VERSION = 0x821B;
		public const int GL_MINOR_VERSION = 0x821C;
		public const int GL_NUM_EXTENSIONS = 0x821D;
		public const int GL_CONTEXT_FLAGS = 0x821E;
		public const int GL_COMPRESSED_RED = 0x8225;
		public const int GL_COMPRESSED_RG = 0x8226;
		public const int GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = 0x00000001;
		public const int GL_RGBA32F = 0x8814;
		public const int GL_RGB32F = 0x8815;
		public const int GL_RGBA16F = 0x881A;
		public const int GL_RGB16F = 0x881B;
		public const int GL_VERTEX_ATTRIB_ARRAY_INTEGER = 0x88FD;
		public const int GL_MAX_ARRAY_TEXTURE_LAYERS = 0x88FF;
		public const int GL_MIN_PROGRAM_TEXEL_OFFSET = 0x8904;
		public const int GL_MAX_PROGRAM_TEXEL_OFFSET = 0x8905;
		public const int GL_CLAMP_READ_COLOR = 0x891C;
		public const int GL_FIXED_ONLY = 0x891D;
		public const int GL_MAX_VARYING_COMPONENTS = 0x8B4B;
		public const int GL_TEXTURE_1D_ARRAY = 0x8C18;
		public const int GL_PROXY_TEXTURE_1D_ARRAY = 0x8C19;
		public const int GL_TEXTURE_2D_ARRAY = 0x8C1A;
		public const int GL_PROXY_TEXTURE_2D_ARRAY = 0x8C1B;
		public const int GL_TEXTURE_BINDING_1D_ARRAY = 0x8C1C;
		public const int GL_TEXTURE_BINDING_2D_ARRAY = 0x8C1D;
		public const int GL_R11F_G11F_B10F = 0x8C3A;
		public const int GL_UNSIGNED_INT_10F_11F_11F_REV = 0x8C3B;
		public const int GL_RGB9_E5 = 0x8C3D;
		public const int GL_UNSIGNED_INT_5_9_9_9_REV = 0x8C3E;
		public const int GL_TEXTURE_SHARED_SIZE = 0x8C3F;
		public const int GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 0x8C76;
		public const int GL_TRANSFORM_FEEDBACK_BUFFER_MODE = 0x8C7F;
		public const int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 0x8C80;
		public const int GL_TRANSFORM_FEEDBACK_VARYINGS = 0x8C83;
		public const int GL_TRANSFORM_FEEDBACK_BUFFER_START = 0x8C84;
		public const int GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = 0x8C85;
		public const int GL_PRIMITIVES_GENERATED = 0x8C87;
		public const int GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x8C88;
		public const int GL_RASTERIZER_DISCARD = 0x8C89;
		public const int GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x8C8A;
		public const int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 0x8C8B;
		public const int GL_INTERLEAVED_ATTRIBS = 0x8C8C;
		public const int GL_SEPARATE_ATTRIBS = 0x8C8D;
		public const int GL_TRANSFORM_FEEDBACK_BUFFER = 0x8C8E;
		public const int GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = 0x8C8F;
		public const int GL_RGBA32UI = 0x8D70;
		public const int GL_RGB32UI = 0x8D71;
		public const int GL_RGBA16UI = 0x8D76;
		public const int GL_RGB16UI = 0x8D77;
		public const int GL_RGBA8UI = 0x8D7C;
		public const int GL_RGB8UI = 0x8D7D;
		public const int GL_RGBA32I = 0x8D82;
		public const int GL_RGB32I = 0x8D83;
		public const int GL_RGBA16I = 0x8D88;
		public const int GL_RGB16I = 0x8D89;
		public const int GL_RGBA8I = 0x8D8E;
		public const int GL_RGB8I = 0x8D8F;
		public const int GL_RED_INTEGER = 0x8D94;
		public const int GL_GREEN_INTEGER = 0x8D95;
		public const int GL_BLUE_INTEGER = 0x8D96;
		public const int GL_RGB_INTEGER = 0x8D98;
		public const int GL_RGBA_INTEGER = 0x8D99;
		public const int GL_BGR_INTEGER = 0x8D9A;
		public const int GL_BGRA_INTEGER = 0x8D9B;
		public const int GL_SAMPLER_1D_ARRAY = 0x8DC0;
		public const int GL_SAMPLER_2D_ARRAY = 0x8DC1;
		public const int GL_SAMPLER_1D_ARRAY_SHADOW = 0x8DC3;
		public const int GL_SAMPLER_2D_ARRAY_SHADOW = 0x8DC4;
		public const int GL_SAMPLER_CUBE_SHADOW = 0x8DC5;
		public const int GL_UNSIGNED_INT_VEC2 = 0x8DC6;
		public const int GL_UNSIGNED_INT_VEC3 = 0x8DC7;
		public const int GL_UNSIGNED_INT_VEC4 = 0x8DC8;
		public const int GL_INT_SAMPLER_1D = 0x8DC9;
		public const int GL_INT_SAMPLER_2D = 0x8DCA;
		public const int GL_INT_SAMPLER_3D = 0x8DCB;
		public const int GL_INT_SAMPLER_CUBE = 0x8DCC;
		public const int GL_INT_SAMPLER_1D_ARRAY = 0x8DCE;
		public const int GL_INT_SAMPLER_2D_ARRAY = 0x8DCF;
		public const int GL_UNSIGNED_INT_SAMPLER_1D = 0x8DD1;
		public const int GL_UNSIGNED_INT_SAMPLER_2D = 0x8DD2;
		public const int GL_UNSIGNED_INT_SAMPLER_3D = 0x8DD3;
		public const int GL_UNSIGNED_INT_SAMPLER_CUBE = 0x8DD4;
		public const int GL_UNSIGNED_INT_SAMPLER_1D_ARRAY = 0x8DD6;
		public const int GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = 0x8DD7;
		public const int GL_QUERY_WAIT = 0x8E13;
		public const int GL_QUERY_NO_WAIT = 0x8E14;
		public const int GL_QUERY_BY_REGION_WAIT = 0x8E15;
		public const int GL_QUERY_BY_REGION_NO_WAIT = 0x8E16;
		public const int GL_BUFFER_ACCESS_FLAGS = 0x911F;
		public const int GL_BUFFER_MAP_LENGTH = 0x9120;
		public const int GL_BUFFER_MAP_OFFSET = 0x9121;
		public const int GL_DEPTH_COMPONENT32F = 0x8CAC;
		public const int GL_DEPTH32F_STENCIL8 = 0x8CAD;
		public const int GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 0x8DAD;
		public const int GL_INVALID_FRAMEBUFFER_OPERATION = 0x0506;
		public const int GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210;
		public const int GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211;
		public const int GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212;
		public const int GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213;
		public const int GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214;
		public const int GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215;
		public const int GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216;
		public const int GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217;
		public const int GL_FRAMEBUFFER_DEFAULT = 0x8218;
		public const int GL_FRAMEBUFFER_UNDEFINED = 0x8219;
		public const int GL_DEPTH_STENCIL_ATTACHMENT = 0x821A;
		public const int GL_MAX_RENDERBUFFER_SIZE = 0x84E8;
		public const int GL_DEPTH_STENCIL = 0x84F9;
		public const int GL_UNSIGNED_INT_24_8 = 0x84FA;
		public const int GL_DEPTH24_STENCIL8 = 0x88F0;
		public const int GL_TEXTURE_STENCIL_SIZE = 0x88F1;
		public const int GL_TEXTURE_RED_TYPE = 0x8C10;
		public const int GL_TEXTURE_GREEN_TYPE = 0x8C11;
		public const int GL_TEXTURE_BLUE_TYPE = 0x8C12;
		public const int GL_TEXTURE_ALPHA_TYPE = 0x8C13;
		public const int GL_TEXTURE_DEPTH_TYPE = 0x8C16;
		public const int GL_UNSIGNED_NORMALIZED = 0x8C17;
		public const int GL_FRAMEBUFFER_BINDING = 0x8CA6;
		public const int GL_DRAW_FRAMEBUFFER_BINDING = 0x8CA6;
		public const int GL_RENDERBUFFER_BINDING = 0x8CA7;
		public const int GL_READ_FRAMEBUFFER = 0x8CA8;
		public const int GL_DRAW_FRAMEBUFFER = 0x8CA9;
		public const int GL_READ_FRAMEBUFFER_BINDING = 0x8CAA;
		public const int GL_RENDERBUFFER_SAMPLES = 0x8CAB;
		public const int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0;
		public const int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1;
		public const int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2;
		public const int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3;
		public const int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4;
		public const int GL_FRAMEBUFFER_COMPLETE = 0x8CD5;
		public const int GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6;
		public const int GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7;
		public const int GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 0x8CDB;
		public const int GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 0x8CDC;
		public const int GL_FRAMEBUFFER_UNSUPPORTED = 0x8CDD;
		public const int GL_MAX_COLOR_ATTACHMENTS = 0x8CDF;
		public const int GL_COLOR_ATTACHMENT0 = 0x8CE0;
		public const int GL_COLOR_ATTACHMENT1 = 0x8CE1;
		public const int GL_COLOR_ATTACHMENT2 = 0x8CE2;
		public const int GL_COLOR_ATTACHMENT3 = 0x8CE3;
		public const int GL_COLOR_ATTACHMENT4 = 0x8CE4;
		public const int GL_COLOR_ATTACHMENT5 = 0x8CE5;
		public const int GL_COLOR_ATTACHMENT6 = 0x8CE6;
		public const int GL_COLOR_ATTACHMENT7 = 0x8CE7;
		public const int GL_COLOR_ATTACHMENT8 = 0x8CE8;
		public const int GL_COLOR_ATTACHMENT9 = 0x8CE9;
		public const int GL_COLOR_ATTACHMENT10 = 0x8CEA;
		public const int GL_COLOR_ATTACHMENT11 = 0x8CEB;
		public const int GL_COLOR_ATTACHMENT12 = 0x8CEC;
		public const int GL_COLOR_ATTACHMENT13 = 0x8CED;
		public const int GL_COLOR_ATTACHMENT14 = 0x8CEE;
		public const int GL_COLOR_ATTACHMENT15 = 0x8CEF;
		public const int GL_COLOR_ATTACHMENT16 = 0x8CF0;
		public const int GL_COLOR_ATTACHMENT17 = 0x8CF1;
		public const int GL_COLOR_ATTACHMENT18 = 0x8CF2;
		public const int GL_COLOR_ATTACHMENT19 = 0x8CF3;
		public const int GL_COLOR_ATTACHMENT20 = 0x8CF4;
		public const int GL_COLOR_ATTACHMENT21 = 0x8CF5;
		public const int GL_COLOR_ATTACHMENT22 = 0x8CF6;
		public const int GL_COLOR_ATTACHMENT23 = 0x8CF7;
		public const int GL_COLOR_ATTACHMENT24 = 0x8CF8;
		public const int GL_COLOR_ATTACHMENT25 = 0x8CF9;
		public const int GL_COLOR_ATTACHMENT26 = 0x8CFA;
		public const int GL_COLOR_ATTACHMENT27 = 0x8CFB;
		public const int GL_COLOR_ATTACHMENT28 = 0x8CFC;
		public const int GL_COLOR_ATTACHMENT29 = 0x8CFD;
		public const int GL_COLOR_ATTACHMENT30 = 0x8CFE;
		public const int GL_COLOR_ATTACHMENT31 = 0x8CFF;
		public const int GL_DEPTH_ATTACHMENT = 0x8D00;
		public const int GL_STENCIL_ATTACHMENT = 0x8D20;
		public const int GL_FRAMEBUFFER = 0x8D40;
		public const int GL_RENDERBUFFER = 0x8D41;
		public const int GL_RENDERBUFFER_WIDTH = 0x8D42;
		public const int GL_RENDERBUFFER_HEIGHT = 0x8D43;
		public const int GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8D44;
		public const int GL_STENCIL_INDEX1 = 0x8D46;
		public const int GL_STENCIL_INDEX4 = 0x8D47;
		public const int GL_STENCIL_INDEX8 = 0x8D48;
		public const int GL_STENCIL_INDEX16 = 0x8D49;
		public const int GL_RENDERBUFFER_RED_SIZE = 0x8D50;
		public const int GL_RENDERBUFFER_GREEN_SIZE = 0x8D51;
		public const int GL_RENDERBUFFER_BLUE_SIZE = 0x8D52;
		public const int GL_RENDERBUFFER_ALPHA_SIZE = 0x8D53;
		public const int GL_RENDERBUFFER_DEPTH_SIZE = 0x8D54;
		public const int GL_RENDERBUFFER_STENCIL_SIZE = 0x8D55;
		public const int GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56;
		public const int GL_MAX_SAMPLES = 0x8D57;
		public const int GL_INDEX = 0x8222;
		public const int GL_TEXTURE_LUMINANCE_TYPE = 0x8C14;
		public const int GL_TEXTURE_INTENSITY_TYPE = 0x8C15;
		public const int GL_FRAMEBUFFER_SRGB = 0x8DB9;
		public const int GL_HALF_FLOAT = 0x140B;
		public const int GL_MAP_READ_BIT = 0x0001;
		public const int GL_MAP_WRITE_BIT = 0x0002;
		public const int GL_MAP_INVALIDATE_RANGE_BIT = 0x0004;
		public const int GL_MAP_INVALIDATE_BUFFER_BIT = 0x0008;
		public const int GL_MAP_FLUSH_EXPLICIT_BIT = 0x0010;
		public const int GL_MAP_UNSYNCHRONIZED_BIT = 0x0020;
		public const int GL_COMPRESSED_RED_RGTC1 = 0x8DBB;
		public const int GL_COMPRESSED_SIGNED_RED_RGTC1 = 0x8DBC;
		public const int GL_COMPRESSED_RG_RGTC2 = 0x8DBD;
		public const int GL_COMPRESSED_SIGNED_RG_RGTC2 = 0x8DBE;
		public const int GL_RG = 0x8227;
		public const int GL_RG_INTEGER = 0x8228;
		public const int GL_R8 = 0x8229;
		public const int GL_R16 = 0x822A;
		public const int GL_RG8 = 0x822B;
		public const int GL_RG16 = 0x822C;
		public const int GL_R16F = 0x822D;
		public const int GL_R32F = 0x822E;
		public const int GL_RG16F = 0x822F;
		public const int GL_RG32F = 0x8230;
		public const int GL_R8I = 0x8231;
		public const int GL_R8UI = 0x8232;
		public const int GL_R16I = 0x8233;
		public const int GL_R16UI = 0x8234;
		public const int GL_R32I = 0x8235;
		public const int GL_R32UI = 0x8236;
		public const int GL_RG8I = 0x8237;
		public const int GL_RG8UI = 0x8238;
		public const int GL_RG16I = 0x8239;
		public const int GL_RG16UI = 0x823A;
		public const int GL_RG32I = 0x823B;
		public const int GL_RG32UI = 0x823C;
		public const int GL_VERTEX_ARRAY_BINDING = 0x85B5;
		public const int GL_CLAMP_VERTEX_COLOR = 0x891A;
		public const int GL_CLAMP_FRAGMENT_COLOR = 0x891B;
		public const int GL_ALPHA_INTEGER = 0x8D97;
		public const int GL_QUADS = 0x0007;
		public const int GL_NONE = 0;
		public const int GL_FRONT_LEFT = 0x0400;
		public const int GL_FRONT_RIGHT = 0x0401;
		public const int GL_BACK_LEFT = 0x0402;
		public const int GL_BACK_RIGHT = 0x0403;
		public const int GL_LEFT = 0x0406;
		public const int GL_RIGHT = 0x0407;
		public const int GL_POINT_SIZE = 0x0B11;
		public const int GL_POINT_SIZE_RANGE = 0x0B12;
		public const int GL_POINT_SIZE_GRANULARITY = 0x0B13;
		public const int GL_LINE_WIDTH = 0x0B21;
		public const int GL_LINE_WIDTH_RANGE = 0x0B22;
		public const int GL_LINE_WIDTH_GRANULARITY = 0x0B23;
		public const int GL_POLYGON_MODE = 0x0B40;
		public const int GL_POLYGON_SMOOTH = 0x0B41;
		public const int GL_CULL_FACE_MODE = 0x0B45;
		public const int GL_FRONT_FACE = 0x0B46;
		public const int GL_DEPTH_RANGE = 0x0B70;
		public const int GL_DEPTH_WRITEMASK = 0x0B72;
		public const int GL_DEPTH_CLEAR_VALUE = 0x0B73;
		public const int GL_DEPTH_FUNC = 0x0B74;
		public const int GL_STENCIL_CLEAR_VALUE = 0x0B91;
		public const int GL_STENCIL_FUNC = 0x0B92;
		public const int GL_STENCIL_VALUE_MASK = 0x0B93;
		public const int GL_STENCIL_FAIL = 0x0B94;
		public const int GL_STENCIL_PASS_DEPTH_FAIL = 0x0B95;
		public const int GL_STENCIL_PASS_DEPTH_PASS = 0x0B96;
		public const int GL_STENCIL_REF = 0x0B97;
		public const int GL_STENCIL_WRITEMASK = 0x0B98;
		public const int GL_VIEWPORT = 0x0BA2;
		public const int GL_BLEND_DST = 0x0BE0;
		public const int GL_BLEND_SRC = 0x0BE1;
		public const int GL_LOGIC_OP_MODE = 0x0BF0;
		public const int GL_DRAW_BUFFER = 0x0C01;
		public const int GL_READ_BUFFER = 0x0C02;
		public const int GL_SCISSOR_BOX = 0x0C10;
		public const int GL_COLOR_CLEAR_VALUE = 0x0C22;
		public const int GL_COLOR_WRITEMASK = 0x0C23;
		public const int GL_DOUBLEBUFFER = 0x0C32;
		public const int GL_STEREO = 0x0C33;
		public const int GL_UNPACK_SWAP_BYTES = 0x0CF0;
		public const int GL_UNPACK_LSB_FIRST = 0x0CF1;
		public const int GL_UNPACK_ROW_LENGTH = 0x0CF2;
		public const int GL_UNPACK_SKIP_ROWS = 0x0CF3;
		public const int GL_UNPACK_SKIP_PIXELS = 0x0CF4;
		public const int GL_PACK_SWAP_BYTES = 0x0D00;
		public const int GL_PACK_LSB_FIRST = 0x0D01;
		public const int GL_PACK_ROW_LENGTH = 0x0D02;
		public const int GL_PACK_SKIP_ROWS = 0x0D03;
		public const int GL_PACK_SKIP_PIXELS = 0x0D04;
		public const int GL_TEXTURE_1D = 0x0DE0;
		public const int GL_TEXTURE_WIDTH = 0x1000;
		public const int GL_TEXTURE_HEIGHT = 0x1001;
		public const int GL_TEXTURE_BORDER_COLOR = 0x1004;
		public const int GL_INT = 0x1404;
		public const int GL_UNSIGNED_INT = 0x1405;
		public const int GL_COLOR = 0x1800;
		public const int GL_DEPTH = 0x1801;
		public const int GL_STENCIL = 0x1802;
		public const int GL_STENCIL_INDEX = 0x1901;
		public const int GL_DEPTH_COMPONENT = 0x1902;
		public const int GL_RED = 0x1903;
		public const int GL_GREEN = 0x1904;
		public const int GL_BLUE = 0x1905;
		public const int GL_POINT = 0x1B00;
		public const int GL_LINE = 0x1B01;
		public const int GL_FILL = 0x1B02;

		#endregion

		// Buffers
		public static Delegates.glBindBuffer glBindBuffer;
		public static Delegates.glBufferData glBufferData;
		public static Delegates.glBufferSubData glBufferSubData;
		public static Delegates.glDeleteBuffers glDeleteBuffers;
		public static Delegates.glGenBuffers glGenBuffers;

		// Framebuffers
		public static Delegates.glBindFramebuffer glBindFramebuffer;
		public static Delegates.glBindRenderbuffer glBindRenderbuffer;
		public static Delegates.glCheckFramebufferStatus glCheckFramebufferStatus;
		public static Delegates.glDeleteFramebuffers glDeleteFramebuffers;
		public static Delegates.glDeleteRenderbuffers glDeleteRenderbuffers;
		public static Delegates.glDrawBuffer glDrawBuffer;
		public static Delegates.glFramebufferRenderbuffer glFramebufferRenderbuffer;
		public static Delegates.glFramebufferTexture2D glFramebufferTexture2D;
		public static Delegates.glGenFramebuffers glGenFramebuffers;
		public static Delegates.glGenRenderbuffers glGenRenderbuffers;
		public static Delegates.glReadBuffer glReadBuffer;
		public static Delegates.glRenderbufferStorage glRenderbufferStorage;

		// Other
		public static Delegates.glCullFace glCullFace;
		public static Delegates.glDisable glDisable;
		public static Delegates.glEnable glEnable;

		// Rendering
		public static Delegates.glBlendFunc glBlendFunc;
		public static Delegates.glClear glClear;
		public static Delegates.glClearColor glClearColor;
		public static Delegates.glDepthFunc glDepthFunc;
		public static Delegates.glDrawElements glDrawElements;
		public static Delegates.glDrawElementsBaseVertex glDrawElementsBaseVertex;
		public static Delegates.glPrimitiveRestartIndex glPrimitiveRestartIndex;
		public static Delegates.glViewport glViewport;

		// Shaders
		public static Delegates.glAttachShader glAttachShader;
		public static Delegates.glBindVertexArray glBindVertexArray;
		public static Delegates.glCompileShader glCompileShader;
		public static Delegates.glCreateProgram glCreateProgram;
		public static Delegates.glCreateShader glCreateShader;
		public static Delegates.glDeleteProgram glDeleteProgram;
		public static Delegates.glDeleteShader glDeleteShader;
		public static Delegates.glDeleteVertexArrays glDeleteVertexArrays;
		public static Delegates.glEnableVertexAttribArray glEnableVertexAttribArray;
		public static Delegates.glGenVertexArrays glGenVertexArrays;
		public static Delegates.glGetActiveUniform glGetActiveUniform;
		public static Delegates.glGetProgramiv glGetProgramiv;
		public static Delegates.glGetProgramInfoLog glGetProgramInfoLog;
		public static Delegates.glGetShaderiv glGetShaderiv;
		public static Delegates.glGetShaderInfoLog glGetShaderInfoLog;
		public static Delegates.glGetUniformLocation glGetUniformLocation;
		public static Delegates.glLinkProgram glLinkProgram;
		public static Delegates.glShaderSource glShaderSource;
		public static Delegates.glUniform1i glUniform1i;
		public static Delegates.glUniform1f glUniform1f;
		public static Delegates.glUniform3f glUniform3f;
		public static Delegates.glUniform4f glUniform4f;
		public static Delegates.glUniform4fv glUniform4fv;
		public static Delegates.glUniformMatrix4fv glUniformMatrix4fv;
		public static Delegates.glUseProgram glUseProgram;
		public static Delegates.glVertexAttribIPointer glVertexAttribIPointer;
		public static Delegates.glVertexAttribPointer glVertexAttribPointer;

		// Textures
		public static Delegates.glActiveTexture glActiveTexture;
		public static Delegates.glBindTexture glBindTexture;
		public static Delegates.glDeleteTextures glDeleteTextures;
		public static Delegates.glGenerateMipmap glGenerateMipmap;
		public static Delegates.glGenTextures glGenTextures;
		public static Delegates.glTexImage2D glTexImage2D;
		public static Delegates.glTexParameteri glTexParameteri;

		private static T GetDelegate<T>() where T : class
		{
			Type type = typeof(T);

			// See https://stackoverflow.com/a/35321707/7281613.
			return Marshal.GetDelegateForFunctionPointer(glfwGetProcAddress(type.Name), type) as T;
		}

		public static unsafe class Delegates
		{
			// Buffers
			public delegate void glBindBuffer(uint target, uint buffer);
			public delegate void glBufferData(uint target, uint size, void* data, uint usage);
			public delegate void glBufferSubData(uint target, int offset, uint size, void* data);
			public delegate void glDeleteBuffers(uint n, uint* buffers);
			public delegate void glGenBuffers(uint n, uint* buffers);

			// Framebuffers
			public delegate void glBindFramebuffer(uint target, uint framebuffer);
			public delegate void glBindRenderbuffer(uint target, uint renderbuffer);
			public delegate uint glCheckFramebufferStatus(uint target);
			public delegate void glDeleteFramebuffers(uint n, uint* framebuffers);
			public delegate void glDeleteRenderbuffers(uint n, uint* renderbuffers);
			public delegate void glDrawBuffer(uint buf);
			public delegate void glFramebufferRenderbuffer(uint target, uint attachment, uint renderbuffertarget,
				uint renderbuffer);
			public delegate void glFramebufferTexture2D(uint target, uint attachment, uint textarget, uint texture,
				int level);
			public delegate void glGenFramebuffers(uint n, uint* ids);
			public delegate void glGenRenderbuffers(uint n, uint* renderbuffers);
			public delegate void glReadBuffer(uint mode);
			public delegate void glRenderbufferStorage(uint target, uint internalformat, uint width, uint height);

			// Other
			public delegate void glCullFace(uint mode);
			public delegate void glDisable(uint cap);
			public delegate void glEnable(uint cap);

			// Rendering
			public delegate void glBlendFunc(uint sfactor, uint dfactor);
			public delegate void glClear(uint mask);
			public delegate void glClearColor(float red, float green, float blue, float alpha);
			public delegate void glDepthFunc(uint func);
			public delegate void glDrawElements(uint mode, uint count, uint type, void* indices);
			public delegate void glDrawElementsBaseVertex(uint mode, uint count, uint type, void* indices, int baseVertex);
			public delegate void glPrimitiveRestartIndex(uint index);
			public delegate void glViewport(int x, int y, uint width, uint height);

			// Shaders
			public delegate void glAttachShader(uint program, uint shader);
			public delegate void glBindVertexArray(uint array);
			public delegate void glCompileShader(uint shader);
			public delegate uint glCreateProgram();
			public delegate uint glCreateShader(uint shaderType);
			public delegate void glDeleteProgram(uint program);
			public delegate void glDeleteShader(uint shader);
			public delegate void glDeleteVertexArrays(uint n, uint* arrays);
			public delegate void glEnableVertexAttribArray(uint index);
			public delegate void glGenVertexArrays(uint n, uint* arrays);
			public delegate void glGetActiveUniform(uint program, uint index, uint bufSize, uint* length, int* size,
				uint* type, byte* name);
			public delegate void glGetProgramiv(uint program, uint pname, int* @params);
			public delegate void glGetProgramInfoLog(uint program, uint maxLength, uint* length, byte* infoLog);
			public delegate void glGetShaderiv(uint shader, uint pname, int* @params);
			public delegate void glGetShaderInfoLog(uint shader, uint maxLength, uint* length, byte* infoLog);
			public delegate int glGetUniformLocation(uint program, byte* name);
			public delegate void glLinkProgram(uint program);
			public delegate void glShaderSource(uint shader, uint count, string[] @string, int* length);
			public delegate void glUniform1i(int location, int v0);
			public delegate void glUniform1f(int location, float v0);
			public delegate void glUniform3f(int location, float v0, float v1, float v2);
			public delegate void glUniform4f(int location, float v0, float v1, float v2, float v3);
			public delegate void glUniform4fv(int location, uint count, float* value);
			public delegate void glUniformMatrix4fv(int location, uint count, bool transpose, float* value);
			public delegate void glUseProgram(uint program);
			public delegate void glVertexAttribIPointer(uint index, int size, uint type, uint stride, void* pointer);
			public delegate void glVertexAttribPointer(uint index, int size, uint type, bool normalized, uint stride,
				void* pointer);

			// Textures
			public delegate void glActiveTexture(uint texture);
			public delegate void glBindTexture(uint target, uint texture);
			public delegate void glDeleteTextures(uint n, uint* textures);
			public delegate void glGenerateMipmap(uint target);
			public delegate void glGenTextures(uint n, uint* textures);
			public delegate void glTexImage2D(uint target, int level, int internalformat, uint width, uint height,
				int border, uint format, uint type, void* data);
			public delegate void glTexParameteri(uint target, uint pname, int param);
		}
	}
}
